# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multi_kernelmatrix <- function(X, h, kernel) {
    .Call('_kernelCpp_multi_kernelmatrix', PACKAGE = 'kernelCpp', X, h, kernel)
}

